/*

Copyright (C) 2008-2022 Michele Martone

This file is part of librsb.

librsb is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

librsb is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public
License along with librsb; see the file COPYING.
If not, see <http://www.gnu.org/licenses/>.

*/
/* @cond INNERDOC */
/* This file was generated by the Makefile */
#ifndef RSB_STRMIF_H_INCLUDED
#define RSB_STRMIF_H_INCLUDED
#include "rsb.h"
#include "rsb_common.h"
#include "rsb_do.h"
rsb_err_t rsb__do_get_matrix_info_from_string(const struct rsb_mtx_t *matrix, const rsb_char_t *mis, void* info, size_t buflen);
rsb_err_t rsb__dump_flags(const rsb_flags_t cflags, const rsb_char_t *pre, const rsb_char_t *intra, const rsb_char_t *post);
#endif /* RSB_STRMIF_H_INCLUDED */
/* @endcond */
