nonProduction_E_AR5_C12.R GISS Model E Tom Clune 02/28/2011

nonProduction_E_AR5_C12  = This is a coarse resolution of E_AR5_M20.
This is for faster testing of code functionality, not scrutinized for "science" purposes.

Preprocessor Options
#define NEW_IO
#define OLD_BCdalbsn
End Preprocessor Options

Object modules:
     ! resolution-specific source codes
Atm36x24                     ! horizontal resolution is 36x24 -> 8x10
AtmL12 STRAT_DUM             ! vertical resolution is 12 layers -> 10mb
DIAG_RES_M
FFT36                         ! Fast Fourier Transform

IO_DRV                              ! new i/o

     ! GISS dynamics with gravity wave drag
ATMDYN MOMEN2ND                     ! atmospheric dynamics
QUS_DRV QUS3D                       ! advection of Q/tracers

#include "latlon_source_files"
#include "modelE4_source_files"
#include "static_ocn_source_files"


Components:
#include "E4_components_nc"    /* without "Ent" */
Ent

Component Options:
OPTS_Ent = ONLINE=YES PS_MODEL=FBB    /* needed for "Ent" only */

Data input files:
#include "IC_36x24_input_files"
#include "static_ocn_1950_36x24_input_files"  /* 1880 for 8x10 needs to be made */
RVR=RD8X10.nc            ! river direction file
NAMERVR=RD8X10.names.txt ! named river outlets

#include "land36x24_input_files"
#include "rad_input_files"        !  CO2profile is disregarded since LM<27
#include "rad_36x24_input_files"

MSU_wts=MSU_SSU_RSS_weights.txt      ! MSU-diag
REG=REG8X10                      ! special regions-diag

Label and Namelist:  (next 2 lines)
EC12 (ModelE4 8x10, 12 layers, 1850 atm, 1950 prescr. ocn)

&&PARAMETERS
#include "static_ocn_params"
#include "sdragC12_params"

xCDpbl=1.
cond_scheme=2   ! newer conductance scheme (N. Kiang) ! not used with Ent

! Increasing U00a decreases the high cloud cover; increasing U00b decreases net rad at TOA
U00a=0.54      ! above 850mb w/o MC region; tune this first to get 30-35% high clouds
U00b=1.00      ! below 850mb and MC regions; then tune this to get rad.balance

WMUI_multiplier = 2.

PTLISO=15.       ! press(mb) above which rad. assumes isothermal layers
H2ObyCH4=1.      ! activates strat.H2O generated by CH4
KSIALB=0         ! 6-band albedo (Hansen) (=1 A.Lacis orig. 6-band alb)
KSOLAR=2         ! 2: use long annual mean file ; 1: use short monthly file

#include "atmCompos_1850_params"
madaer=3         ! 3: updated aerosols          ; 1: default sulfates/aerosols
aer_rad_forc=0
cloud_rad_forc=1
crops_yr=-1

DTsrc=1800.      ! cannot be changed after a run has been started
DT=450.          ! could be 900 if DTsrc=3600.  do not forget nda5 et al.
! parameters that control the Shapiro filter
DT_XUfilter=450. ! Shapiro filter on U in E-W direction; usually same as DT
DT_XVfilter=450. ! Shapiro filter on V in E-W direction; usually same as DT
DT_YVfilter=0.   ! Shapiro filter on V in N-S direction
DT_YUfilter=0.   ! Shapiro filter on U in N-S direction

NIsurf=1         ! (surf.interaction NIsurf times per physics time step)
NRAD=5           ! radiation (every NRAD'th physics time step)
#include "diag_params"

Nssw=2           ! until diurnal diags are fixed, Nssw has to be even
Ndisk=480
&&END_PARAMETERS

 &INPUTZ
 YEARI=1949,MONTHI=12,DATEI=1,HOURI=0, ! pick IYEAR1=YEARI (default) or < YEARI
 YEARE=1949,MONTHE=12,DATEE=2,HOURE=0,     KDIAG=12*0,9,
 ISTART=2,IRANDI=0, YEARE=1949,MONTHE=12,DATEE=1,HOURE=1,
/
