.TH "RsbLib" 3 "Sat Jan 29 2022" "RsbLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RsbLib \- Class initializing/finalizing \fClibrsb\fP state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rsb\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Err_t  = void> Err_t \fBset_opt_str\fP (const rsb_char_t *opnp, const rsb_char_t *opvp)"
.br
.ti -1c
.RI "template<typename Err_t  = void> Err_t \fBset_opt\fP (enum rsb_opt_t iof, const void *iop)"
.br
.ti -1c
.RI "template<typename Err_t  = void> Err_t \fBget_opt\fP (enum rsb_opt_t iof, void *iop) const"
.br
.ti -1c
.RI "rsb_string_t \fBget_opt\fP (enum rsb_opt_t iof) const"
.br
.ti -1c
.RI "template<typename Err_t  = void> Err_t \fBset_num_threads\fP (rsb_int_t nt)"
.br
.ti -1c
.RI "rsb_int_t \fBget_num_threads\fP (void) const"
.br
.ti -1c
.RI "template<typename Err_t  = void> Err_t \fBreinit\fP (struct rsb_initopts *iop)"
.br
.ti -1c
.RI "\fBRsbLib\fP (bool verbose)"
.br
.ti -1c
.RI "\fBRsbLib\fP (void)"
.br
.ti -1c
.RI "size_t \fBmeminfo\fP (void)"
.br
.ti -1c
.RI "\fB~RsbLib\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class initializing/finalizing \fClibrsb\fP state\&. 

Before creating any \fC\fBRsbMatrix\fP\fP objects, make sure you have initialized \fClibrsb\fP by creating one single \fC\fBRsbLib\fP\fP object\&. Similarly, \fC\fBRsbMatrix\fP\fP object shall leave scope after the \fC\fBRsbLib\fP\fP object has been deallocated\&.
.PP
Several \fClibrsb\fP options can be queried or changed via e\&.g\&. \fBget_opt()\fP, \fBset_opt()\fP, \fBget_num_threads()\fP, \fBset_num_threads()\fP\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RsbLib::RsbLib (bool verbose)\fC [inline]\fP"
Initialize librsb\&. 
.PP
\fBSee also:\fP
.RS 4
\fBrsb_lib_reinit()\fP\&.
.RE
.PP

.SS "RsbLib::RsbLib (void)\fC [inline]\fP"
Initialize librsb\&. 
.PP
\fBSee also:\fP
.RS 4
\fBrsb_lib_reinit()\fP\&.
.RE
.PP

.SS "RsbLib::~RsbLib (void)\fC [inline]\fP"
Destructor: finalize \fClibrsb\fP\&.
.PP
This is being invoked at the end of the scope of a \fC\fBRsbLib\fP\fP object: typically at application's end\&.
.SH "Member Function Documentation"
.PP 
.SS "rsb_int_t RsbLib::get_num_threads (void) const\fC [inline]\fP"
Indirect interface to rsb_lib_get_opt\&.
.SS "template<typename Err_t  = void> Err_t RsbLib::get_opt (enum rsb_opt_t iof, void * iop) const\fC [inline]\fP"
Interface to rsb_lib_get_opt\&.
.SS "rsb_string_t RsbLib::get_opt (enum rsb_opt_t iof) const\fC [inline]\fP"
Interface to rsb_lib_get_opt\&.
.SS "size_t RsbLib::meminfo (void)\fC [inline]\fP"
Provide memory debug info from librsb and return usage amount\&. Only effective if librsb configured accordingly\&.
.PP
On error, throw an exception\&.
.SS "template<typename Err_t  = void> Err_t RsbLib::reinit (struct rsb_initopts * iop)\fC [inline]\fP"
Interface to \fBrsb_lib_reinit()\fP\&.
.SS "template<typename Err_t  = void> Err_t RsbLib::set_num_threads (rsb_int_t nt)\fC [inline]\fP"
Indirect interface to rsb_lib_set_opt\&.
.SS "template<typename Err_t  = void> Err_t RsbLib::set_opt (enum rsb_opt_t iof, const void * iop)\fC [inline]\fP"
Interface to rsb_lib_set_opt\&.
.SS "template<typename Err_t  = void> Err_t RsbLib::set_opt_str (const rsb_char_t * opnp, const rsb_char_t * opvp)\fC [inline]\fP"
Interface to rsb_lib_set_opt_str\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RsbLib from the source code\&.
