/*

Copyright (C) 2008-2022 Michele Martone

This file is part of librsb.

librsb is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

librsb is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
License for more details.

You should have received a copy of the GNU Lesser General Public
License along with librsb; see the file COPYING.
If not, see <http://www.gnu.org/licenses/>.

*/
/* @cond INNERDOC */
/* This file was generated by the Makefile */
#include "rsb.h"
#include "rsb_common.h"
rsb_err_t rsb__stropts_set(const rsb_char_t *opn, const rsb_char_t *arg)
{ rsb_err_t errval=RSB_ERR_NO_ERROR; if(!opn || !arg)goto err;
if(0 == strcmp(opn,"RSB_IO_WANT_SORT_METHOD")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_SORT_METHOD,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_CACHE_BLOCKING_METHOD")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_CACHE_BLOCKING_METHOD,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_SUBDIVISION_MULTIPLIER")){ rsb_real_t val = rsb__util_atof(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_SUBDIVISION_MULTIPLIER,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_BOUNDED_BOX_COMPUTATION")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_BOUNDED_BOX_COMPUTATION,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_EXECUTING_THREADS")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_EXECUTING_THREADS,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_EXTRA_VERBOSE_INTERFACE")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_EXTRA_VERBOSE_INTERFACE,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_MEMORY_HIERARCHY_INFO_STRING")){ const rsb_char_t* val = arg; RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_MEMORY_HIERARCHY_INFO_STRING,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_LEAF_LEVEL_MULTIVEC")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_LEAF_LEVEL_MULTIVEC,&val,errval); goto done;}
if(0 == strcmp(opn,"RSB_IO_WANT_VERBOSE_TUNING")){ rsb_int_t val = rsb__util_atoi(arg); RSB_DO_REINIT_SINGLE_VALUE_SET(RSB_IO_WANT_VERBOSE_TUNING,&val,errval); goto done;}
done:
return errval;
err: return RSB_ERR_GENERIC_ERROR;
}
/* @endcond */
